export const GET_ALL_CATS_REQUESTED = 'GET_ALL_CATS_REQUESTED';
export const GET_ALL_CATS_SUCCESS = 'GET_ALL_CATS_SUCCESS';
export const GET_ALL_CATS_ERROR = 'GET_ALL_CATS_ERROR';

export const UPDATE_CAT_REQUESTED = 'UPDATE_CAT_REQUESTED';
export const UPDATE_CAT_SUCCESS = 'UPDATE_CAT_SUCCESS';
export const UPDATE_CAT_ERROR = 'UPDATE_CAT_ERROR';

